apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: activemq-kubernetes
  labels:
    app: activemq-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: activemq-kubernetes
  template:
    metadata:
      labels:
        app: activemq-kubernetes
    spec:
      containers:
        - image: padmaraglaunchpad/activemq-kubernetes:latest
          name: activemq-kubernetes
          ports:
            - containerPort: 8161
              name: admin
            - containerPort: 61616
              name: broker
            - containerPort: 5672
              name: amqp
            - containerPort: 61613
              name: stomp
            - containerPort: 1883
              name: mqtt
            - containerPort: 61614
              name: websocket